<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitafd11982c36816e2cb96bbf392ea4f09
{
    public static $prefixLengthsPsr4 = array (
        'G' => 
        array (
            'Genius\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Genius\\' => 
        array (
            0 => __DIR__ . '/..' . '/simivar/genius-php/src/Genius',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitafd11982c36816e2cb96bbf392ea4f09::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitafd11982c36816e2cb96bbf392ea4f09::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
